import 'package:flutter/cupertino.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final List<IconData> incomeIcons = [
  FontAwesomeIcons.dollarSign,
  FontAwesomeIcons.sackDollar,
  FontAwesomeIcons.coins,
  FontAwesomeIcons.moneyBill,
  FontAwesomeIcons.moneyCheck,
  FontAwesomeIcons.piggyBank,
  FontAwesomeIcons.chartLine,
  FontAwesomeIcons.handHoldingUsd,
  FontAwesomeIcons.cashRegister,
  FontAwesomeIcons.wallet,
  FontAwesomeIcons.businessTime,
  FontAwesomeIcons.chartBar,
  FontAwesomeIcons.creditCard,
  FontAwesomeIcons.handHolding,
  FontAwesomeIcons.moneyBillWave,
  FontAwesomeIcons.moneyBillAlt,
  FontAwesomeIcons.moneyCheckAlt,
  FontAwesomeIcons.donate,
  FontAwesomeIcons.chartPie,
  FontAwesomeIcons.invision,
];

final List<IconData> expenseIcons = [
  FontAwesomeIcons.shoppingCart,
  FontAwesomeIcons.creditCard,
  FontAwesomeIcons.cartArrowDown,
  FontAwesomeIcons.cartPlus,
  FontAwesomeIcons.donate,
  FontAwesomeIcons.moneyBillWave,
  FontAwesomeIcons.moneyCheck,
  FontAwesomeIcons.moneyBill,
  FontAwesomeIcons.wallet,
  FontAwesomeIcons.handHoldingUsd,
  FontAwesomeIcons.piggyBank,
  FontAwesomeIcons.cashRegister,
  FontAwesomeIcons.shoppingBag,
  FontAwesomeIcons.store,
  FontAwesomeIcons.coins,
  FontAwesomeIcons.gift,
  FontAwesomeIcons.handHolding,
  FontAwesomeIcons.receipt,
  FontAwesomeIcons.cartShopping,
];

final List<IconData> walletIcons = [
  FontAwesomeIcons.wallet,
  FontAwesomeIcons.moneyBill,
  FontAwesomeIcons.moneyBillWave,
  FontAwesomeIcons.moneyBillAlt,
  FontAwesomeIcons.creditCard,
  FontAwesomeIcons.sackDollar,
  FontAwesomeIcons.piggyBank,
  FontAwesomeIcons.handHoldingUsd,
  FontAwesomeIcons.coins,
  FontAwesomeIcons.cashRegister,
  FontAwesomeIcons.moneyCheck,
  FontAwesomeIcons.chartLine,
  FontAwesomeIcons.chartBar,
  FontAwesomeIcons.businessTime,
  FontAwesomeIcons.dollarSign,
  FontAwesomeIcons.handHolding,
  FontAwesomeIcons.donate,
  FontAwesomeIcons.bank,
  FontAwesomeIcons.safari,
  FontAwesomeIcons.fileInvoiceDollar,
];
